name: Generate manifest.json

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - "**/*.md"
      - ".github/workflows/generate-manifest.yml"

permissions:
  contents: write

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'auto: update manifest')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate manifest.json (scan all *.md)
        run: |
          node - <<'NODE'
          import fs from 'fs';
          import path from 'path';

          const ROOT = process.cwd();

          const IGNORE_DIRS = new Set([
            '.git','.github','node_modules','dist','build','.next','out'
          ]);

          function walk(dir) {
            const entries = fs.readdirSync(dir, { withFileTypes: true });
            let items = [];
            for (const e of entries) {
              if (e.name.startsWith('.DS_Store')) continue;
              const full = path.join(dir, e.name);
              const rel  = path.relative(ROOT, full).split(path.sep).join('/');

              if (e.isDirectory()) {
                if (IGNORE_DIRS.has(e.name)) continue;
                items = items.concat(walk(full));
              } else {
                const ext = path.extname(e.name).toLowerCase();
                if (ext === '.md' || ext === '.markdown') {
                  items.push(rel);
                }
              }
            }
            return items;
          }

          const files = walk(ROOT).sort((a,b)=>a.localeCompare(b,'en',{numeric:true}));

          // defaultDoc: pilih README.md (root) kalau ada; kalau tidak, file pertama
          const hasRootReadme = files.includes('README.md');
          const defaultDoc = hasRootReadme ? 'README.md' : (files[0] || null);

          const manifest = {
            generatedAt: new Date().toISOString(),
            defaultDoc,
            files, // array path relatif
          };

          fs.writeFileSync('manifest.json', JSON.stringify(manifest, null, 2));
          console.log('Wrote manifest.json with', files.length, 'entries. Default:', defaultDoc);
          NODE

      - name: Commit & Push manifest.json
        run: |
          # kalau .gitignore mengabaikan manifest.json, paksa add -f
          git add -f manifest.json
          if git diff --cached --quiet --exit-code; then
            echo "No changes to commit."
            exit 0
          fi
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "auto: update manifest"
          git push
